/*CREATE DATABASE boboniortdb; */

CREATE TABLE INSURANCE (
  INSURANCE_NAME varchar(30),
  INSURANCE_ADRESS1 varchar(50),
  INSURANCE_ADRESS2 varchar(50),
  INSURANCE_ZIPCODE varchar(15),
  INSURANCE_TOWN varchar(50),
  INSURANCE_COUNTRY varchar(20)
);

CREATE TABLE USER_TAB (
  UUID_USER UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  USER_IDENTIFICATION varchar (10)      NOT NULL,
  USER_PASSWORD varchar (30)            NOT NULL,
  USER_AUTHORIZATION varchar (1)
);

CREATE TABLE FUNCTION_TAB (
  UUID_FUNCTION UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  FUNCTION_LARGELABEL varchar (80),
  FUNCTION_ROOT  varchar (36)
);

CREATE TABLE CUSTOMER (
  UUID_CUSTOMER UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  CUSTOMER_GENDER VARCHAR(10),
  CUSTOMER_LASTNAME VARCHAR(50),
  CUSTOMER_FIRSTNAME VARCHAR(50),
  CUSTOMER_ADRESS1 VARCHAR(50),
  CUSTOMER_ADRESS2 VARCHAR(50),
  CUSTOMER_ZIPCODE VARCHAR(15),
  CUSTOMER_TOWN VARCHAR(50),
  CUSTOMER_COUNTRY VARCHAR(20),
  CUSTOMER_PHONE VARCHAR(10),
  CUSTOMER_MAIL VARCHAR(50),
  CUSTOMER_BIRTH_DATE DATE,
  CUSTOMER_DOCTOR VARCHAR(50),
  CUSTOMER_CODE_SECU BIGINT,
  CUSTOMER_CODE_IBAN VARCHAR(34),
  CUSTOMER_NBCHILDREN INTEGER,
  CUSTOMER_COUPLE BOOLEAN,
  CUSTOMER_CREATE_DATE DATE,
  CUSTOMER_UPDATE_DATE DATE,
  CUSTOMER_CLOSE_DATE DATE,
  CUSTOMER_ACTIVE VARCHAR(1)
);